version: "3"
services:
  app_mongo:
    image: mongo:5.0.8
    container_name: githubx-mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/db/mongo/db:/data/db
      - ~/db/mongo/conf:/data/configdb
      - ~/db/mongo/back:/data/backup
    environment:
      - MONGO_INITDB_DATABASE=githubx
  app:
    container_name: githubx-api
    restart: always
    image: riskers/githubx-api
    working_dir: /app
    links:
      - app_mongo
    depends_on:
      - app_mongo
    ports:
      - "8910:8910"
